# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Deploy"

# Set up GitHub Environments with "Selected branches" limit and environment URL as a variable
# https://github.com/ORG/REPO/settings/environments

on:  # yamllint disable-line rule:truthy
    workflow_dispatch:
        inputs:
            target_env:
                description: "Environment to deploy to"
                type: "environment"
                required: true
            db_wipe:
                description: "Wipe database? (REBOOT/No)"
                type: "string"
                required: false
                default: "No"

permissions: {}

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}-deploy-${{ inputs.target_env }}"
    cancel-in-progress: false

jobs:
    call_deployment:
        name: "Deployment"
        uses: "./.github/workflows/reusable-deployment.yml"
        with:
            target_env: "${{ inputs.target_env }}"
            db_wipe: "${{ inputs.db_wipe }}"
        secrets: "inherit"
